version: 2

project_name: bhelper

env:
  - CFLAGS=-isystem /usr/include
  - PKG_CONFIG_ALLOW_CROSS=1

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - id: "bhelper"
    binary: bhelper
    builder: rust
    flags:
      - --release
      - --package=bhelper
      # - --features=self_update
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-pc-windows-gnu

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}-{{ .Target }}
    ids:
      - bhelper

changelog:
  disable: true

release:
  footer: >-
    ---
    Released by [GoReleaser](https://goreleaser.com)
